/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Asset } from "./Asset";
import { AssetCountArgs } from "./AssetCountArgs";
import { AssetFindManyArgs } from "./AssetFindManyArgs";
import { AssetFindUniqueArgs } from "./AssetFindUniqueArgs";
import { CreateAssetArgs } from "./CreateAssetArgs";
import { UpdateAssetArgs } from "./UpdateAssetArgs";
import { DeleteAssetArgs } from "./DeleteAssetArgs";
import { InventoryFindManyArgs } from "../../inventory/base/InventoryFindManyArgs";
import { Inventory } from "../../inventory/base/Inventory";
import { PurchaseOrder } from "../../purchaseOrder/base/PurchaseOrder";
import { AssetService } from "../asset.service";
@graphql.Resolver(() => Asset)
export class AssetResolverBase {
  constructor(protected readonly service: AssetService) {}

  async _assetsMeta(
    @graphql.Args() args: AssetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Asset])
  async assets(@graphql.Args() args: AssetFindManyArgs): Promise<Asset[]> {
    return this.service.assets(args);
  }

  @graphql.Query(() => Asset, { nullable: true })
  async asset(
    @graphql.Args() args: AssetFindUniqueArgs
  ): Promise<Asset | null> {
    const result = await this.service.asset(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Asset)
  async createAsset(@graphql.Args() args: CreateAssetArgs): Promise<Asset> {
    return await this.service.createAsset({
      ...args,
      data: {
        ...args.data,

        purchaseOrder: args.data.purchaseOrder
          ? {
              connect: args.data.purchaseOrder,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Asset)
  async updateAsset(
    @graphql.Args() args: UpdateAssetArgs
  ): Promise<Asset | null> {
    try {
      return await this.service.updateAsset({
        ...args,
        data: {
          ...args.data,

          purchaseOrder: args.data.purchaseOrder
            ? {
                connect: args.data.purchaseOrder,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Asset)
  async deleteAsset(
    @graphql.Args() args: DeleteAssetArgs
  ): Promise<Asset | null> {
    try {
      return await this.service.deleteAsset(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Inventory], { name: "inventories" })
  async findInventories(
    @graphql.Parent() parent: Asset,
    @graphql.Args() args: InventoryFindManyArgs
  ): Promise<Inventory[]> {
    const results = await this.service.findInventories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => PurchaseOrder, {
    nullable: true,
    name: "purchaseOrder",
  })
  async getPurchaseOrder(
    @graphql.Parent() parent: Asset
  ): Promise<PurchaseOrder | null> {
    const result = await this.service.getPurchaseOrder(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
