/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PurchaseOrderService } from "../purchaseOrder.service";
import { PurchaseOrderCreateInput } from "./PurchaseOrderCreateInput";
import { PurchaseOrder } from "./PurchaseOrder";
import { PurchaseOrderFindManyArgs } from "./PurchaseOrderFindManyArgs";
import { PurchaseOrderWhereUniqueInput } from "./PurchaseOrderWhereUniqueInput";
import { PurchaseOrderUpdateInput } from "./PurchaseOrderUpdateInput";
import { AssetFindManyArgs } from "../../asset/base/AssetFindManyArgs";
import { Asset } from "../../asset/base/Asset";
import { AssetWhereUniqueInput } from "../../asset/base/AssetWhereUniqueInput";

export class PurchaseOrderControllerBase {
  constructor(protected readonly service: PurchaseOrderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PurchaseOrder })
  async createPurchaseOrder(
    @common.Body() data: PurchaseOrderCreateInput
  ): Promise<PurchaseOrder> {
    return await this.service.createPurchaseOrder({
      data: {
        ...data,

        supplier: data.supplier
          ? {
              connect: data.supplier,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        orderDate: true,
        orderNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PurchaseOrder] })
  @ApiNestedQuery(PurchaseOrderFindManyArgs)
  async purchaseOrders(
    @common.Req() request: Request
  ): Promise<PurchaseOrder[]> {
    const args = plainToClass(PurchaseOrderFindManyArgs, request.query);
    return this.service.purchaseOrders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        orderDate: true,
        orderNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PurchaseOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async purchaseOrder(
    @common.Param() params: PurchaseOrderWhereUniqueInput
  ): Promise<PurchaseOrder | null> {
    const result = await this.service.purchaseOrder({
      where: params,
      select: {
        createdAt: true,
        id: true,
        orderDate: true,
        orderNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PurchaseOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePurchaseOrder(
    @common.Param() params: PurchaseOrderWhereUniqueInput,
    @common.Body() data: PurchaseOrderUpdateInput
  ): Promise<PurchaseOrder | null> {
    try {
      return await this.service.updatePurchaseOrder({
        where: params,
        data: {
          ...data,

          supplier: data.supplier
            ? {
                connect: data.supplier,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          orderDate: true,
          orderNumber: true,
          status: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PurchaseOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePurchaseOrder(
    @common.Param() params: PurchaseOrderWhereUniqueInput
  ): Promise<PurchaseOrder | null> {
    try {
      return await this.service.deletePurchaseOrder({
        where: params,
        select: {
          createdAt: true,
          id: true,
          orderDate: true,
          orderNumber: true,
          status: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/assets")
  @ApiNestedQuery(AssetFindManyArgs)
  async findAssets(
    @common.Req() request: Request,
    @common.Param() params: PurchaseOrderWhereUniqueInput
  ): Promise<Asset[]> {
    const query = plainToClass(AssetFindManyArgs, request.query);
    const results = await this.service.findAssets(params.id, {
      ...query,
      select: {
        cost: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,
        purchaseDate: true,

        purchaseOrder: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/assets")
  async connectAssets(
    @common.Param() params: PurchaseOrderWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        connect: body,
      },
    };
    await this.service.updatePurchaseOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/assets")
  async updateAssets(
    @common.Param() params: PurchaseOrderWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        set: body,
      },
    };
    await this.service.updatePurchaseOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/assets")
  async disconnectAssets(
    @common.Param() params: PurchaseOrderWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        disconnect: body,
      },
    };
    await this.service.updatePurchaseOrder({
      where: params,
      data,
      select: { id: true },
    });
  }
}
