/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProcurementService } from "../procurement.service";
import { ProcurementCreateInput } from "./ProcurementCreateInput";
import { Procurement } from "./Procurement";
import { ProcurementFindManyArgs } from "./ProcurementFindManyArgs";
import { ProcurementWhereUniqueInput } from "./ProcurementWhereUniqueInput";
import { ProcurementUpdateInput } from "./ProcurementUpdateInput";

export class ProcurementControllerBase {
  constructor(protected readonly service: ProcurementService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Procurement })
  async createProcurement(
    @common.Body() data: ProcurementCreateInput
  ): Promise<Procurement> {
    return await this.service.createProcurement({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Procurement] })
  @ApiNestedQuery(ProcurementFindManyArgs)
  async procurements(@common.Req() request: Request): Promise<Procurement[]> {
    const args = plainToClass(ProcurementFindManyArgs, request.query);
    return this.service.procurements({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Procurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async procurement(
    @common.Param() params: ProcurementWhereUniqueInput
  ): Promise<Procurement | null> {
    const result = await this.service.procurement({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Procurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProcurement(
    @common.Param() params: ProcurementWhereUniqueInput,
    @common.Body() data: ProcurementUpdateInput
  ): Promise<Procurement | null> {
    try {
      return await this.service.updateProcurement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Procurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProcurement(
    @common.Param() params: ProcurementWhereUniqueInput
  ): Promise<Procurement | null> {
    try {
      return await this.service.deleteProcurement({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
